baseurl = "https://www.pawangaria.com/"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
publishDir = "docs"
title = "Testing, Automation, Programming and Latest Technology Articles"
description = "Resources for Java and Automation testing developers - Provides article about webdriver, automation testing, framework design and java."
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
googleAnalytics = "UA-110208829-1"
enableRobotsTXT= true
#DisqueCommenting
disqusShortname = "www-pawangaria-com"

paginate = 6

[sitemap]
  changefreq = "weekly"
  priority = 0.9
  filename = "sitemap.xml"

[Params]
  subtitle = "This blog comprises topics about Information Technology"
  description = "Resources for Java and Automation testing developers - Provides article about webdriver, automation testing, framework design and java."
  keywords = "Selenium,WebDriver,ChromeDriver,Automation Testing,Java,TestNG,TestRail,Quality Assurance,HTTP,JSON,Automation testing tutorials"
  home = "PawanGaria.com"
  welcomeText ="Welcome"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
  recentArticlesLimit = 5

#[[Params.bigimg]]
 #src = "img/triangle.jpg"
  #desc = "Triangle"
  #position = "center top"



[Author]
  name = "Pawan garia"
  website = "www.pawangaria.com"
  email = "pawangaria@gmail.com"
  facebook = "pawan.garia"
  linkedin = "pawan-garia-a947a24a"
[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
