baseurl = "https://www.pawangaria.com/"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
publishDir = "docs"
title = "Welcome To My Blog"
description = "The blog of Pawan Garia about information technology, he is an automation testing architect and design expert and web developer."
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
googleAnalytics = "UA-110208829-1"

home = "Home"

[Params]
  subtitle = "My blog contains topics about information technology"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Pawan garia"
  website = "www.pawangaria.com"
  email = "pawangaria@gmail.com"
  facebook = "pawan.garia"
  linkedin = "pawan-garia-a947a24a"
[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
